bbr_version_viewer_homepage:
    path:  /
    defaults: { _controller: BbrVersionViewerBundle:Default:index }

bbr_version_viewer_LoadInstance:
    path:  /loadApp/{appKey}/{env}
    defaults: { _controller: BbrVersionViewerBundle:Default:loadAppInstance, _format: json }
bbr_version_viewer_LoadApplication:
    path:  /loadApp/{appKey}/
    defaults: { _controller: BbrVersionViewerBundle:Default:loadApplication, _format: json }

bbr_version_viewer_help:
    path:  /help
    defaults: { _controller: BbrVersionViewerBundle:Default:help  }
bbr_version_viewer_feedback:
    path:  /feedback
    defaults: { _controller: BbrVersionViewerBundle:Default:feedback  }
